#build:system_studio:
#  image: ubuntu
#  before_script:
#    - apt-get update -qq
#    # Installer needs wget, cpio, sample program needs cmake, icc needs g++
#    - apt-get install -qqq -y cmake cpio g++ wget
#    - IC_LICENSE_TYPE=SS ./intel-compilers/install-linux.sh

#  script:
#    - source /opt/intel/bin/iccvars.sh -arch intel64 || true
#    - icc -v
#    - mkdir build; cd build
#    - CC=icc CXX=icpc cmake ../src/c-example
#    - make
#    - make test

build:parallel_studio_xe:
  image: ubuntu
  before_script:
    - apt-get update -qq
    # Installer needs wget, cpio, sample program needs cmake, icc needs g++
    - apt-get install -qqq -y cmake cpio g++ openssl wget
    - ./is-installers/linux/is-install.sh

  script:
    - source /opt/intel/bin/iccvars.sh -arch intel64 || true
    - icc -v
    - mkdir build; cd build
    - CC=icc CXX=icpc cmake ../src/c-example
    - make
    - make test

