build:system_studio:
  image: ubuntu
  before_script:
    - apt-get update -qq
    # Installer needs cpio, sample program needs cmake
    - apt-get install -qq -y cpio cmake
    - IC_LICENSE_TYPE=SS ./intel-compilers/install-linux.sh

  script:
    - source /opt/intel/bin/iccvars.sh -arch intel64
    - icc -v
    - mkdir build; cd build
    - CC=icc CXX=icpc cmake ../src/c-example
    - make
    - make test

build:parallel_studio_xe:
  image: ubuntu
  before_script:
    - apt-get update -qq
    # Installer needs cpio, sample program needs cmake
    - apt-get install -qq -y cpio cmake
    - IC_LICENSE_TYPE=PSXE ./intel-compilers/install-linux.sh

  script:
    - source /opt/intel/bin/iccvars.sh -arch intel64
    - icc -v
    - mkdir build; cd build
    - CC=icc CXX=icpc cmake ../src/c-example
    - make
    - make test

build:parallel_studio_xe_fortrann:
  image: ubuntu
  before_script:
    - apt-get update -qq
    # Installer needs cpio, sample program needs cmake
    - apt-get install -qq -y cpio cmake
    - IC_LICENSE_TYPE=PSXE_FORTRAN ./intel-compilers/install-linux.sh

  script:
    - source /opt/intel/bin/iccvars.sh -arch intel64
    - icc -v
    - mkdir build; cd build
    - CC=icc CXX=icpc cmake ../src
    - make
    - make test
