language: c
sudo: required

before_install:
  - sudo apt-get update -qq
  # Installer needs cpio, sample program needs cmake
  - sudo apt-get install -qq -y cpio cmake
  - sudo .intel-compilers/install-linux.sh

script:
  - source /opt/intel/bin/iccvars.sh -arch intel64
  - icc -v
  - mkdir build; cd build
  - FC=ifort CC=icc CXX=icpc cmake ../src
  - make
  - make test
