image: ubuntu

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq cmake cpio g++ openssl wget
  - sudo --preserve-env ./is-installers/linux/is-install.sh

test_script:
  - source /opt/intel/bin/iccvars.sh -arch intel64
  - icc -v
  - mkdir build; cd build
  - FC=ifort CC=icc CXX=icpc cmake ../src
  - make
  - make test

build: off
